### ISSUE TITLE
Module not found: Error: Can't resolve '....publicRDKit_minimal.1.2.13.js' when building on Windows

### ISSUE THREAD

**Issue by drassokhin** [rdkit/rdkit-structure-renderer#5]
`npm run build` results in the `Module not found: Error: Can't resolve '....publicRDKit_minimal.1.2.13.js'`  error when building on Windows.

This is due to the \ (backslash) character used on Windows as the path separator. There's a trivial fix: in webpack.config.js replace 
```javascript
MINIMALLIB_PATH: `'${path.join("..", "..", "public", `RDKit_minimal.${version}.js`)}'`,
```
with
```javascript
MINIMALLIB_PATH: `'${path.join("..", "..", "public", `RDKit_minimal.${version}.js`)}'`.replaceAll('\\', '/'),
```
or simply get rid of path.join altogether and hardcode ../../public/RDKit ...

**Comment by ptosco** [comment]
@drassokhin Thank you for reporting, this should now be fixed.
